# Generated by Django 2.2.3 on 2020-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201103_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favourites',
            field=models.IntegerField(default=0),
        ),
    ]
